CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    cancel_reason VARCHAR(500),
    no_show_reason VARCHAR(500),
    checked_in_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_appointments_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_appointments_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT ck_appointments_period CHECK (end_at > start_at),
    CONSTRAINT ck_appointments_status CHECK (
        status IN ('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELED', 'NO_SHOW')
    )
);

CREATE INDEX idx_appointments_professional ON appointments (professional_id);
CREATE INDEX idx_appointments_customer ON appointments (customer_id);
CREATE INDEX idx_appointments_service ON appointments (service_id);
CREATE INDEX idx_appointments_start_at ON appointments (start_at);
CREATE INDEX idx_appointments_end_at ON appointments (end_at);
CREATE INDEX idx_appointments_status ON appointments (status);
CREATE INDEX idx_appointments_professional_period_status
    ON appointments (professional_id, start_at, end_at, status);
