CREATE TABLE availability_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_availability_rules_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT ck_availability_rules_day CHECK (
        day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    ),
    CONSTRAINT ck_availability_rules_period CHECK (end_time > start_time)
);

CREATE TABLE schedule_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    exception_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    type VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_schedule_exceptions_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT ck_schedule_exceptions_type CHECK (type IN ('AVAILABLE', 'BLOCKED')),
    CONSTRAINT ck_schedule_exceptions_period CHECK (end_time > start_time)
);

CREATE INDEX idx_availability_rules_professional_day_active
    ON availability_rules (professional_id, day_of_week, active, start_time);
CREATE INDEX idx_schedule_exceptions_professional_date
    ON schedule_exceptions (professional_id, exception_date, start_time);
