@baseUrl = http://localhost:8080
@accessToken = paste_access_token_here

### Login como admin local
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@atendeja.local",
  "password": "change_me_admin"
}

### Login como atendente local
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "attendant@atendeja.local",
  "password": "change_me_attendant"
}

### Endpoint protegido com Bearer JWT
GET {{baseUrl}}/api/v1/appointments?page=0&size=10
Authorization: Bearer {{accessToken}}

### Operação administrativa protegida
POST {{baseUrl}}/api/v1/services
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Consulta protegida",
  "description": "Exemplo para validar role.",
  "durationMinutes": 45,
  "bufferMinutes": 15,
  "price": 150.00
}
